#ifndef _H_DEBUG_SERVER_CONFIG_
#define _H_DEBUG_SERVER_CONFIG_

#define SERVICE_PORT    9541
#define COMMAND_PORT    9545
#define GDBSERVER_PORT  9549

#define VERSION         "1.2.0"

#define COMMAND_GDB_REGISTER        0x01
#define COMMAND_GDBSERVER_ATTACH    0x02
#define COMMAND_STRACE_ATTACH       0x03
#define COMMAND_GET_ADDRESS         0x04
#define COMMAND_GDB_LOGOUT          0x05
#define COMMAND_RUN_SERVICE         0x06

#endif